/**
 * Schedules a large campaign to show how the planner spreads load across hour windows.
 *
 *   npm run load-test -- --user you@example.com --count 1000 --delay 2000 --limit 200
 *   npm run load-test -- --user you@example.com --count 1000 --start +5 --cleanup
 *
 * --user     email of an existing account (log in once through the UI first)
 * --count    recipients to generate (default 1000)
 * --delay    milliseconds between two emails (default 2000)
 * --limit    campaign hourly limit (default 200)
 * --start    minutes from now for the first send, e.g. +60 (default +60, so nothing sends by accident)
 * --cleanup  remove the campaign and its jobs again once the plan has been printed
 */
import 'dotenv/config';
import { prisma } from '../src/lib/prisma.js';
import { redis } from '../src/lib/redis.js';
import { createCampaign } from '../src/modules/campaigns/campaigns.service.js';
import { emailJobId, emailQueue } from '../src/modules/queue/email-queue.js';
import { hourWindowStart } from '../src/modules/scheduling/schedule-plan.js';

function arg(name: string, fallback: string): string {
  const index = process.argv.indexOf(`--${name}`);
  return index === -1 ? fallback : (process.argv[index + 1] ?? fallback);
}

async function main(): Promise<void> {
  const userEmail = arg('user', '');
  const count = Number(arg('count', '1000'));
  const delayMs = Number(arg('delay', '2000'));
  const hourlyLimit = Number(arg('limit', '200'));
  const startInMinutes = Number(arg('start', '+60'));
  const cleanup = process.argv.includes('--cleanup');

  if (!userEmail) throw new Error('--user <email> is required');

  const user = await prisma.user.findUnique({ where: { email: userEmail.toLowerCase() } });
  if (!user) throw new Error(`No user with email ${userEmail}; log in through the UI first`);

  const sender = await prisma.sender.findFirst({ where: { userId: user.id } });
  if (!sender)
    throw new Error('The user has no senders yet; open the dashboard once to provision them');

  const recipients = Array.from({ length: count }, (_, i) => ({
    email: `load-${String(i + 1).padStart(5, '0')}@example.test`,
    name: `Load Test ${i + 1}`,
  }));

  const startAt = new Date(Date.now() + startInMinutes * 60_000);
  const startedAt = Date.now();

  const result = await createCampaign({
    userId: user.id,
    senderId: sender.id,
    subject: `Load test: ${count} recipients`,
    bodyHtml: '<p>This message was generated by scripts/load-test.ts.</p>',
    recipients,
    startAt,
    delayMs,
    hourlyLimit,
  });

  const elapsed = Date.now() - startedAt;

  const rows = await prisma.email.findMany({
    where: { campaignId: result.campaignId },
    select: { scheduledAt: true },
  });
  const histogram = new Map<number, number>();
  for (const row of rows) {
    const window = hourWindowStart(row.scheduledAt.getTime());
    histogram.set(window, (histogram.get(window) ?? 0) + 1);
  }

  console.log(`\nCampaign ${result.campaignId}`);
  console.log(
    `  ${result.total} rows + ${result.total} delayed jobs written in ${elapsed} ms (queued: ${result.queued})`,
  );
  console.log(
    `  effective delay ${result.effective.delayMs} ms, hourly limit ${result.effective.hourlyLimit}`,
  );
  console.log(
    `  first send ${result.firstAt.toISOString()}, last send ${result.lastAt.toISOString()}\n`,
  );
  console.log('  Emails per hour window:');
  for (const [window, n] of [...histogram.entries()].sort((a, b) => a[0] - b[0])) {
    console.log(
      `    ${new Date(window).toISOString().slice(0, 16)}Z  ${'#'.repeat(Math.ceil(n / 10)).padEnd(20)} ${n}`,
    );
  }

  const delayed = await emailQueue.getDelayedCount();
  console.log(`\n  Delayed jobs now in Redis: ${delayed}`);

  if (cleanup) {
    const ids = await prisma.email.findMany({
      where: { campaignId: result.campaignId },
      select: { id: true },
    });
    await Promise.all(ids.map(({ id }) => emailQueue.remove(emailJobId(id))));
    await prisma.campaign.delete({ where: { id: result.campaignId } });
    console.log(`  Cleaned up: removed ${ids.length} jobs and the campaign.\n`);
  } else {
    console.log(
      '  Left in place. Start the worker to watch them go out, or re-run with --cleanup.\n',
    );
  }
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await Promise.allSettled([emailQueue.close(), prisma.$disconnect(), redis.quit()]);
  });
